print("cars ferrari")
print("singers ciara")
print("celebrities")
print("web servers")
print("actress jennifer lopez")
print("cabin crew")
print("hunters")
print("favourite animal")
print("alphanumeric")
print("fruits")
print("choda family")
print("evil thoughts")
print("hungry wolves")
print("sexy ladies")
print("matatus")
print("nyoka beginners")
