print("name")
print("age")
print("gender")
print("email")
print("phone number")
print("work place")
print("sibling")
print("place")
print("years")
print("hobbies")
print("type of music")
print("fiancee")
print("number of cars")
print("host")
print("bettin")
print("fire flake")
print("getting dunked")
print("sparxx")
print("phantom")
print("worse noise escalade")
print("skycraper")
